### PR TITLE
Allow Factory consumers to skip Retrofit instance.

### PR DESCRIPTION
**Pull request by nostra13**

### CODE REVIEW

**Comment by JakeWharton** [comment]
This is never null. What are you trying to do?

**Comment by nostra13** [comment]
Doing magic:
`converterFactory.responseBodyConverter(type, emptyArray(), null)`
Wow, it's null.

I use single `Converter.Factory` for Retrofit and outside Retrofit for own purpose. Incoming Retrofit instance isn't used in your Factory so it's safe to make it nullable. 
I understand, maybe this Factory is not intended for independent usage outside Retrofit infrastructure but I have the case.

**Comment by nostra13** [comment]
@JakeWharton What's the decision?

**Comment by JakeWharton** [comment]
This parameter type is marked as `@NonNull` in Retrofit. This project just needs to opt-in to the JSR-305 nullability honoring of the Kotlin compiler which would make a change like this impossible (and would also ensure we don't ever disagree elsewhere).

**Comment by JakeWharton** [comment]
Adding in https://github.com/JakeWharton/retrofit2-kotlinx-serialization-converter/pull/29

**Comment by nostra13** [comment]
I agree about JSR-305 but I can't found `@NonNull` annotations you mentioned in `Converter.Factory`:
https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/Converter.java

**Comment by JakeWharton** [comment]
It's the default on the whole package: https://github.com/square/retrofit/blob/65de04d1da61f9e8124956f6fff8902fc81d05e2/retrofit/src/main/java/retrofit2/package-info.java#L13

**Comment by nostra13** [comment]
Ok

**Pull request closed without merging**
